### ISSUE TITLE
Cleos show zero staked tokens if user hasn't used bw

### ISSUE THREAD

**Issue by afalaleev** [cyberway/cyberway#1038]
Before bw usage:
![image](https://user-images.githubusercontent.com/27198658/62099191-7567b180-b2b7-11e9-8ca2-59c44948b763.png)

After bw usage:
![image](https://user-images.githubusercontent.com/27198658/62099220-8dd7cc00-b2b7-11e9-8007-8d7611cd22e7.png)

**Comment by s-medvedev** [comment]
Fixed in #1057
