### ISSUE TITLE
Nodeos fails with an error: table_info.hpp:28: cyberway::chaindb::table_name_t cyberway::chaindb::table_info::table_name() const: Assertion `is_valid()' failed

### ISSUE THREAD

**Issue by e-schepachev** [cyberway/cyberway#1175]
Build type: Debug
Steps:
1) Remove data directory. 
2) Start nodeos with stale production and without genesis: nodeosd --contracts-console --config-dir ./ -d ./data.dir -e --producer-name=cyber 
3) Load a cyber.bios contract.
4) Stop the nodeos
5) Remove the nodeos data directory
6) Start the nodeos with the same configuration
7) Try to load the cyber.bios contract again if the nodeos hasn't been failed

nodeos fails on assert. No stacktrace provided

**Comment by boostmultifruit** [comment]
@e-schepachev My steps:

1. Remove data dir.

2.
```
nodeos --contracts-console --config-dir ./ -d ./data.dir -e --producer-name=cyber --plugin eosio::chain_api_plugin
```
3.  
```
./cleos set contract bob /root/commun.contracts/cyberway.contracts/build/cyber.bios -p bob@active
```
4. Ctrl+C
5. Remove data.dir.
6. Try 2 again.
7. Not failed, try 3 again.
8. Not failed.

**Comment by e-schepachev** [comment]
stack trace

 6# 0x000000000123C9B3 at /home/eugin/projects/cyberway/libraries/chain/include/cyberway/chaindb/table_info.hpp:29
 7# 0x0000000001345FBA at /home/eugin/projects/cyberway/libraries/chain/chaindb/mongo_driver.cpp:770
 8# 0x0000000001341435 at /home/eugin/projects/cyberway/libraries/chain/chaindb/mongo_driver.cpp:617
 9# 0x0000000001339E0C at /home/eugin/projects/cyberway/libraries/chain/chaindb/mongo_driver.cpp:1069
10# 0x00000000012AC0CB at /home/eugin/projects/cyberway/libraries/chain/chaindb/abi_info.cpp:431
11# 0x00000000012F36C5 at /home/eugin/projects/cyberway/libraries/chain/chaindb/value_verifier.cpp:47
12# 0x00000000012F33E7 at /home/eugin/projects/cyberway/libraries/chain/chaindb/value_verifier.cpp:20
13# 0x00000000012F315D at /home/eugin/projects/cyberway/libraries/chain/chaindb/value_verifier.cpp:63
14# 0x0000000001263039 at /home/eugin/projects/cyberway/libraries/chain/chaindb/undo_state.cpp:601
15# 0x000000000126219B at /home/eugin/projects/cyberway/libraries/chain/chaindb/undo_state.cpp:348
16# 0x0000000001260945 at /home/eugin/projects/cyberway/libraries/chain/chaindb/undo_state.cpp:1023
17# 0x000000000124FDF7 at /home/eugin/projects/cyberway/libraries/chain/chaindb/undo_state.cpp:349
18# 0x000000000124CD65 at /home/eugin/projects/cyberway/libraries/chain/chaindb/undo_state.cpp:1089
19# 0x000000000123C6A1 at /home/eugin/projects/cyberway/libraries/chain/chaindb/controller.cpp:546
20# 0x000000000123754A at /home/eugin/projects/cyberway/libraries/chain/chaindb/controller.cpp:1047
21# 0x00000000012374F5 at /home/eugin/projects/cyberway/libraries/chain/chaindb/controller.cpp:1014
22# 0x0000000000CF6F4E at /home/eugin/projects/cyberway/libraries/fc/include/fc/optional.hpp:242
23# 0x0000000000CF6F05 at /home/eugin/projects/cyberway/libraries/fc/include/fc/optional.hpp:28
24# 0x0000000000D38C95 at /home/eugin/projects/cyberway/libraries/chain/include/eosio/chain/transaction_context.hpp:64
25# 0x0000000000CE1273 at /home/eugin/projects/cyberway/libraries/chain/controller.cpp:1223
26# 0x0000000000CC938E at /home/eugin/projects/cyberway/libraries/chain/controller.cpp:1975
27# 0x0000000000C165BD at /home/eugin/projects/cyberway/plugins/producer_plugin/producer_plugin.cpp:417
28# 0x0000000000C38ADC at /home/eugin/projects/cyberway/plugins/producer_plugin/producer_plugin.cpp:354
29# 0x0000000000C38A79 at /home/eugin/opt/boost/include/boost/asio/bind_executor.hpp:414
30# 0x0000000000C38A59 at /home/eugin/projects/cyberway/plugins/chain_plugin/../../libraries/appbase/include/appbase/execution_priority_queue.hpp:143
31# 0x00000000004DC514 at /home/eugin/projects/cyberway/libraries/appbase/include/appbase/execution_priority_queue.hpp:39
32# 0x00000000004D6AE9 at /home/eugin/projects/cyberway/libraries/appbase/application.cpp:385
33# 0x00000000004C4510 at /home/eugin/projects/cyberway/programs/nodeos/main.cpp:107
