### ISSUE TITLE
API-метод идентификации пользователя

### ISSUE THREAD

**Issue by Format-X22** [cyberway/cyberway#261]
Необходим метод, который позволит проверить что именно указанный пользователь подписал указанные данные.

Предполагаемый формат запроса:
- Имя пользователя (или, вероятно, идентификатор? или вообще без него?)
- Публичный ключ (или хватит имени пользователя? это было бы удобно)
- Строка-секрет (генерируется нашим сервисом авторизации)
- Подпись строки-секрета приватным ключом пользователя

Предполагаемый ответ:
- true/false, обозначающий верна ли подпись (если нужен и ключ и пара - ещё проверка что именно указанный пользователь владелец указанного публичного ключа)

**Comment by zxcat** [comment]
Так это можно проверить на клиенте/сервисе авторизации

**Comment by Format-X22** [comment]
Тогда нужна инструкция как это сделать.

**Comment by zxcat** [comment]
Должен быть готовый метод в либе, типа https://github.com/EOSIO/eosjs-ecc#verify

**Comment by afalaleev** [comment]
We need additional microservices for the blockchain node:
- authority service
- history service 
- and others ....

In eosio blockchain such function are realized by plugins in the blockchain node, but we have an external storage, so we can move functionality in external services and release node from such functionality.

**Comment by afalaleev** [comment]
Answer on question was given
