### ISSUE TITLE
Data packing fails in chaindb if the database does not contain the field specified in the ABI-description

### ISSUE THREAD

**Issue by s-medvedev** [cyberway/cyberway#322]
**Impact:** smart-contract can't read data with missing fields in database

**STR:**
1. Load smart-contract version 1
2. Save data
3. Load smart-contract version 2 (with extended fields in ABI-description)
4. Try to load data saved in step 2

**Actual result:**
Data packing fails
```{"code":500,"message":"Internal Service Error","error":{"code":3015014,"name":"pack_exception","what":"Pack data exception","details":[{"message":"Missing field 'payments' in input object while processing struct 'account'","file":"abi_serializer.cpp","line_number":499,"method":"_variant_to_binary"},{"message":"","file":"abi_serializer.cpp","line_number":526,"method":"_variant_to_binary"},{"message":"","file":"abi_serializer.cpp","line_number":540,"method":"_variant_to_binary"},{"message":"pending console output: ","file":"apply_context.cpp","line_number":68,"method":"exec_one"}]}}```

**Expected result:**
Data packed successfully with default values for missing fields

**Comment by afalaleev** [comment]
This is strategy of smart contract, which can use binary_extension.
