### ISSUE TITLE
Cleos 'set contract' always thinks that ABI is changed

### ISSUE THREAD

**Issue by afalaleev** [cyberway/cyberway#811]
There is wrong reading of old ABI in `set contract` command, cleos decodes ABI as binary stream:
https://github.com/GolosChain/cyberway/blob/0c6c5645dbf8ff15053a4297660857231ff1775a/programs/cleos/main.cpp#L2751

When it is in base64-encoded format. The correct reading should be like this:
https://github.com/GolosChain/cyberway/blob/0c6c5645dbf8ff15053a4297660857231ff1775a/programs/cleos/main.cpp#L2287

**Comment by zxcat** [comment]
PR #814
